### ISSUE TITLE
key and iv need to be encode as hex string?

### ISSUE THREAD

**Issue by QuangAnh84** [ositano/flutter_3des#1]
Hi guys, 

What is the format of key and iv parameter? 
Currently I have key and encrypt message from  other (they generate from C# server). But I cannot decrypt it.
The Initialization Vector to decrypt the message: byte[] { 0, 0, 0, 0, 0, 0, 0, 0 } 
I away got the error message: java.security.InvalidKeyException: Wrong key size

```
Future<String> decryptTDES_b(String data, String password) async {
     const iv = "00000000";
     var decryptBase64 = await Flutter3des.decryptFromBase64(data, md5.convert(utf8.encode(password)).toString(), iv: iv);
     return decryptBase64;
  }
```

Can someone help me?

**Comment by ositano** [comment]
@QuangAnh84 3DES needs 64 bit IVs. You can encode them to hex or write a function to handle it while you pass the value
